#ifndef INCLUDE_CONSTANTS_CPP
#define INCLUDE_CONSTANTS_CPP

int WINDOW_WIDTH = 1024;
int WINDOW_HEIGHT = 768;
int VIEWPORT_WIDTH = WINDOW_WIDTH;
int VIEWPORT_HEIGHT = WINDOW_HEIGHT;
int FRAMEBUFFER_WIDTH = VIEWPORT_WIDTH * 2;
int FRAMEBUFFER_HEIGHT = VIEWPORT_HEIGHT * 2;

#endif